meta_product_name: "Coachby"
meta_title: "Coachby - Train Better, Be Greater"
meta_description: "CoachBy streamlines the management and communication of performance information. Our platform centralises athlete’s data and allows trainers to create custom programs for them."
meta_image: "banner_contentfb.jpg" # should exist in `app/assets/images/`
